apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: cv-ingress
spec:
    rules:
        - host: lazari.dev
          http:
              paths:
                  - backend:
                        serviceName: my-cv-node
                        servicePort: 3000
        - host: graph.lazari.dev
          http:
              paths:
                  -   backend:
                          serviceName: kube-prometheus-stack-grafana
                          servicePort: 80
